(require 'ctxmenu)
(require 'el-expectations)

(expectations
  (desc "get-condifion-matched-commands default")
  (expect '(forward-char forward-word)
    (let ((cmds '(forward-char forward-word forward-symbol vc-rename-file))
          (src '()))
      (ctxmenu::get-condition-matched-commands cmds src)))
  (desc "get-condifion-matched-commands excludes")
  (expect '(forward-word)
    (let ((cmds '(forward-char forward-word forward-symbol vc-rename-file))
          (src '((excludes . (forward-char)))))
      (ctxmenu::get-condition-matched-commands cmds src)))
  (desc "get-condifion-matched-commands exclude-regexp")
  (expect '(forward-char)
    (let ((cmds '(forward-char forward-word forward-symbol vc-rename-file))
          (src '((exclude-regexp . "word\\'"))))
      (ctxmenu::get-condition-matched-commands cmds src)))
  (desc "get-condifion-matched-commands include-regexp")
  (expect '(forward-symbol)
    (let ((cmds '(forward-char forward-word forward-symbol vc-rename-file))
          (src '((include-regexp . "symbol\\'"))))
      (ctxmenu::get-condition-matched-commands cmds src)))
  (desc "get-condifion-matched-commands include-menu")
  (expect '(forward-char forward-word vc-rename-file)
    (let ((cmds '(forward-char forward-word forward-symbol vc-rename-file))
          (src '((include-menu . t))))
      (ctxmenu::get-condition-matched-commands cmds src)))
  (desc "get-condifion-matched-commands include-all")
  (expect '(forward-char forward-word forward-symbol vc-rename-file)
    (let ((cmds '(forward-char forward-word forward-symbol vc-rename-file))
          (src '((include-all . t))))
      (ctxmenu::get-condition-matched-commands cmds src)))
  )

